This is makeindex, version 2.15 [TeX Live 2015] (kpathsea + Thai support).
Scanning style file ./main2test.ist.............................done (29 attributes redefined, 0 ignored).
Scanning input file main2test.acn....done (26 entries accepted, 0 rejected).
Sorting entries....done (131 comparisons).
Generating output file main2test.acr....done (70 lines written, 0 warnings).
Output written in main2test.acr.
Transcript written in main2test.alg.
